/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yinxm_ndk_MainActivity */

#ifndef _Included_cn_yinxm_ndk_MainActivity
#define _Included_cn_yinxm_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yinxm_ndk_MainActivity
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yinxm_ndk_MainActivity_getStrFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
