/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yinxm_ndk_KeyUtil */

#ifndef _Included_cn_yinxm_ndk_KeyUtil
#define _Included_cn_yinxm_ndk_KeyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yinxm_ndk_KeyUtil
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yinxm_ndk_KeyUtil_getKey
  (JNIEnv *, jclass);

/*
 * Class:     cn_yinxm_ndk_KeyUtil
 * Method:    callJavaStaticMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yinxm_ndk_KeyUtil_callJavaStaticMethod
  (JNIEnv *, jclass);

/*
 * Class:     cn_yinxm_ndk_KeyUtil
 * Method:    callJavaObjectMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yinxm_ndk_KeyUtil_callJavaObjectMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
